-- Add missing columns to api_keys table
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS user_email TEXT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS service TEXT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS encrypted_key TEXT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS key_valid BOOLEAN DEFAULT false;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS last_validated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Add missing columns to api_key_audit_log table
ALTER TABLE api_key_audit_log ADD COLUMN IF NOT EXISTS user_email TEXT;
ALTER TABLE api_key_audit_log ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE api_key_audit_log ADD COLUMN IF NOT EXISTS service TEXT;
ALTER TABLE api_key_audit_log ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE api_key_audit_log ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
